apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: web-view-access
  namespace: web
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: web-edit-access
  namespace: web
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "update", "patch"] # "create", "delete"
